name: Release styles

on:
    push:
      tags:
        - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
            ref: main
      - name: Build Caraffa
        run: |
            ./caraffa_style.sh 
            cd ..
            zip -r caraffa-${{github.ref_name}} ./*
      - name: Release Caraffa
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: caraffa-${{github.ref_name}}
